# Generated by Django 3.2.8 on 2022-03-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn_parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choreography',
            name='name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
