# Generated by Django 3.2.8 on 2023-09-20 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn_parser', '0002_choreography_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choreography',
            options={'verbose_name': 'choreography', 'verbose_name_plural': 'choreographies'},
        ),
    ]
