# Generated by Django 3.2.8 on 2023-09-12 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bpmn_parser', '0002_choreography_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunningInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.IntegerField(choices=[(0, 'Off Chain'), (1, 'On Chain')], help_text='the on-chain engine uses the distributed ledger, while the off-chain engine uses only local data structures (mostly for testing purposes)')),
                ('label', models.CharField(blank=True, max_length=500, null=True)),
                ('choreography', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bpmn_parser.choreography')),
            ],
        ),
    ]
