# Generated by Django 3.2.8 on 2023-09-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runninginstance',
            options={'verbose_name': 'running instance', 'verbose_name_plural': 'running instances'},
        ),
        migrations.AddField(
            model_name='runninginstance',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
