# Generated by Django 3.2.8 on 2023-09-20 22:56

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_alter_runninginstance_engine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='runninginstance',
            name='enforcer',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True),
        ),
    ]
