# Generated by Django 3.2.8 on 2023-09-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_runninginstance_enforcer'),
    ]

    operations = [
        migrations.AddField(
            model_name='runninginstance',
            name='execution_ended',
            field=models.DateTimeField(blank=True, help_text='The time when the instance was started, if it was ever executed', null=True),
        ),
        migrations.AddField(
            model_name='runninginstance',
            name='execution_started',
            field=models.DateTimeField(blank=True, help_text='The time when the instance was started, if it was ever executed', null=True),
        ),
    ]
