# Generated by Django 3.2.8 on 2023-09-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_auto_20230921_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='runninginstance',
            name='input_string',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runninginstance',
            name='output_string',
            field=models.TextField(blank=True, null=True),
        ),
    ]
