# Generated by Django 3.2.8 on 2023-09-21 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20230921_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runninginstance',
            old_name='input_string',
            new_name='input_events',
        ),
        migrations.RenameField(
            model_name='runninginstance',
            old_name='output_string',
            new_name='output_events',
        ),
    ]
